server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true #Spring 2.5버전 부터 테이블 생성보다 sql 문이 먼저 실행되도록 우선순위가 변경 되었음. - 이를 해결하기 위함
  h2:
    console:
      enable:true
  datasource:
    url: jdbc:h2:mem:testdb
  messages:
    basename: messages
  security:
    user:
      name: taemin
      password: rla2647

management:
  endpoints:
    web:
      exposure:
        include: "*"


